#!/bin/bash

start_date=$(tail -n 1 $1/match_log.csv | grep -oE "[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}")
./abg_challonge.py -c ../abg.ini -d"$start_date" -o "$1/../all_abg_log.csv" rip && ./abg_stats.py -e"Champion and Challenger" $1 < $1/../all_abg_log.csv
